on:
  workflow_dispatch:
  workflow_run:
    workflows: ["update-data"]
    branches: ["main", "master"]
    types: [completed]

name: deploy
jobs:
  render:
    name: update-shinyapp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: r-lib/actions/setup-r@v1
        use-public-rspm: true
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install remotes, and the updated package
        env:
          GITHUB_PAT: ${{ secrets.PAT }}
        run: |
          install.packages(c(
            "remotes", "rsconnect", "shiny", "tidyr", "import", "reactable",
            "shinydashboard", "lubridate", "shinycssloaders"
          ))
          remotes::install_local()
        shell: Rscript {0}
      - name: Execute Script
        env:
          GITHUB_PAT: ${{ secrets.PAT }}
          SHINYAPPS_TOKEN: ${{ secrets.SAT }}
          SHINYAPPS_SECRET: ${{ secrets.SAS }}
        run: |
          Rscript "data-raw/update-app.R"
