on:
  worlflow_dispatch:
  schedule:
    - cron: "0 0,12 * * *"

name: update-data

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install remotes, and the local package
        env:
          GITHUB_PAT: ${{ secrets.PAT }}
        run: |
          install.packages("remotes", repos = "https://packagemanager.rstudio.com/all/__linux__/focal/latest")
          install.packages("usethis", repos = "https://packagemanager.rstudio.com/all/__linux__/focal/latest")
          remotes::install_local(".", repos = "https://packagemanager.rstudio.com/all/__linux__/focal/latest")
        shell: Rscript {0}
      - name: Execute Script
        run: |
          Rscript "data-raw/update-data.R"
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m 'Update data' || echo "Update data"
          git push origin || echo "Update data"

